"""initial tables

Revision ID: 921f869ab613
Revises: 
Create Date: 2025-11-16 21:36:20.307361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f869ab613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Governorates',
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Date_Create', sa.DateTime(), nullable=False),
    sa.Column('Date_Update', sa.DateTime(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Users',
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password_Hash', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Date_Create', sa.DateTime(), nullable=False),
    sa.Column('Date_Update', sa.DateTime(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Regions',
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Governorate_Id', sa.String(length=36), nullable=False),
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Date_Create', sa.DateTime(), nullable=False),
    sa.Column('Date_Update', sa.DateTime(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Governorate_Id'], ['Governorates.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Clients_Messages',
    sa.Column('Full_Name', sa.String(length=100), nullable=False),
    sa.Column('Phone_Number', sa.String(length=20), nullable=False),
    sa.Column('Region_Id', sa.String(length=36), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('House_Number', sa.String(length=50), nullable=False),
    sa.Column('Message', sa.Text(), nullable=True),
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Date_Create', sa.DateTime(), nullable=False),
    sa.Column('Date_Update', sa.DateTime(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Region_Id'], ['Regions.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Phone_Number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clients_Messages')
    op.drop_table('Regions')
    op.drop_table('Users')
    op.drop_table('Governorates')
    # ### end Alembic commands ###
